### ISSUE TITLE
Question: Can we restrict the visibility of the survey to selected group of user?

### ISSUE THREAD

**Issue by snag365** [github/copilot-survey-engine#24]
Before we implement the survey engine, we had below questions:
1. Is the survey configured at Org level or repo level? 
2. if configured for a single repo, does all the PR in that repo invokes the survey invoked?
3. Do we get any setting to chose who can view or get the survey? or will the  survey be visible for all users?

Thanks in Advance.

**Comment by mageroni** [comment]
Hi @snag365!

Here the answers:
1. Both option are possible. This survey engine is deployed as a GitHub App (details in the _Setup. Deploy on your own environment_ part of the readme), so you could decide which scope you'd like to install it. 
2. As of the current logic, yes. It will be triggered for all PR that get closed/merged in the repo. That's why the first question for the developer is whether he/she used Copilot. Using the new [Copilot API](https://docs.github.com/en/free-pro-team@latest/rest/copilot/copilot-for-business?apiVersion=2022-11-28#list-all-copilot-for-business-seat-assignments-for-an-organization), I'm working on modifying the logic to add a filter for the users that have the Copilot seat assigned, let me know if you'll be interested!
3. As a GitHub Issue, the survey will be available for all users that are able to see the Issues of a given repo, although only one user will be assigned to answer it (this is the PR author by default). The results on the other hand will be stored in a Database of your choosing (details in the _Setup. Deploy on your own environment_ part of the readme) and therefore you could decide who has access to such database.
